In [2]:
#loading modules and pandas
import pandas as pd
import numpy as np
from pathlib import Path
df = pd.read_excel(r"GSAF5_arm.xls", engine="xlrd")
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Checking overall stats by dates, not cleaning, but asking code to "eat" it unified
df = df.copy()

df["Date"] = df["Date"].astype(str)
df["date_parsed"] = pd.to_datetime(
    df["Date"], 
    errors="coerce", 
    format="mixed")

day = df["day"]   = df["date_parsed"].dt.day
month = df["month"] = df["date_parsed"].dt.month
year = df["year"]  = df["date_parsed"].dt.year

#df_year = df["year"].value_counts()
#df_month = df["month"].value_counts()
#df_day = df["day"].value_counts()

#print(df_day)
#print(df_month)
#print(df_year)
df.head(5)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,date_parsed,day,month,year
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,NaN,NaN,NaN,NaN,NaN,NaN,1-03-18,18.0,3.0,1.0
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,NaN,NaN,NaN,NaN,NaN,NaN,1-03-14,14.0,3.0,1.0
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,NaN,NaN,NaN,NaN,NaN,NaN,1-03-10,10.0,3.0,1.0
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,NaN,NaN,NaN,NaN,NaN,NaN,1-03-05,5.0,3.0,1.0
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,NaN,NaN,NaN,NaN,NaN,NaN,1-02-22,22.0,2.0,1.0

In [4]:
#We estimate the amount of cleaning work
df['Injury'].unique()

<StringArray>
[                                                                        'Injuries to both legs and feet',
                                                                                         'Minor injuries',
                                                                          'None reported damage to board',
                                                                          'Lacerations elbow and abdomen',
                                                                              'Deep wounds arms and legs',
                                                                         'Minor puncture wounds to thigh',
                                                            'Right thigh and lower leg stripped of flesh',
                                                              'No injury shark knocked man of  his board',
                                                                          'Puncture wounds to right knee',
                                                                              'Minor cuts and abrasions ',
 ...
                                                                                       'Shark bumped him',
                                                                                              'Fatal x 2',
                                                             'No injury to occupant; shark capsized boat',
                                                                                     '2-inch lacerations',
                                                    'FATAL, 18 people  were killed by sharks, 2 survived',
                                                                                             '"Lost leg"',
 'FATAL, body not recovered but shark was caught with the man's loincloth in its gut shortly afterwards.',
                                                                         'FATAL, leg stripped of flesh  ',
                                      'FATAL, knocked overboard by tail of shark & carried off by shark ',
                                   'FATAL. "Shark bit him in half, carrying away the lower extremities" ']
Length: 4194, dtype: str

In [5]:
#We estimate the amount of cleaning work
print(len(df['Injury'].unique()))

4194

In [6]:
# & - and
# | - or
# ~ - not

In [7]:
#Our main Filter to get 1st step, gitting out only lost hands
armfiler = (
    (
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'torn off', case=False, na=False))
        |
        (df['Injury'].str.contains(r'hand', case=False, na=False) & df['Injury'].str.contains(r'bitten off', case=False, na=False))
        |
        (df['Injury'].str.contains(r'hand', case=False, na=False) & df['Injury'].str.contains(r'removed', case=False, na=False))
        |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'torn off', case=False, na=False))
            |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'amputated', case=False, na=False))
        |
        (df['Injury'].str.contains(r'hand', case=False, na=False) & df['Injury'].str.contains(r'amputated', case=False, na=False))    
         |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'taken off', case=False, na=False))
        |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'taking', case=False, na=False)) 
        |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'missing', case=False, na=False)) 
         |
        (df['Injury'].str.contains(r'arm', case=False, na=False) & df['Injury'].str.contains(r'bitten off', case=False, na=False))    
        )
    &
    ~df['Injury'].str.contains(r'fatal', case=False, na=False) & ~df['Injury'].str.contains(r'death', case=False, na=False) & ~df['Injury'].str.contains(r'died', case=False, na=False))
unique_with_arm = df.loc[armfiler, 'Injury'].dropna()

print(len(unique_with_arm))

45

In [8]:
#Cutting out only targeted data part
arm = df[df['Injury'].isin(unique_with_arm)].copy()
arm.reset_index(inplace=True)
arm.shape

(45, 28)

In [9]:
#Saving it into file
arm.to_csv('arm_cleaned.csv', index=False)

In [10]:
#After making some manual correction loading renamed corrected version
arm = pd.read_csv('arm_cleaned_aftermanual.csv')

In [11]:
#Manual cleaning block for Injury column by searching key words and updating main mask filter
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
df_not_arm = df.loc[~armfiler]

In [12]:
df_not_arm.shape

(7037, 27)

In [13]:
df_not_arm['Injury'].head(30)

0                        Injuries to both legs and feet
1                                        Minor injuries
2                         None reported damage to board
3                         Lacerations elbow and abdomen
4                             Deep wounds arms and legs
5                        Minor puncture wounds to thigh
6           Right thigh and lower leg stripped of flesh
7             No injury shark knocked man of  his board
8                         Puncture wounds to right knee
9                             Minor cuts and abrasions
10                        None reported damage to board
11                                 Serious Leg injuries
12                                 Serious leg injuries
13            Minor puncture wounds to upper left thigh
14                          Puncture mark to left thumb
16                                             Unknlown
17                              Injuries to upper limbs
18    One leg missing and also a portion of the othe...
19                                       None to report
20    Taken by shark body recovered with multiple in...
21                                          Hand Injury
22                                 Bite wounds to thigh
23                                 Serious leg injuries
24                                           Not stated
25                                    No Injury to self
26                                   Deep Gash to bicep
27                                     Injuries to legs
28          Laceration on top and undermeath right foot
29                             Lacerations to right leg
30                                   Severe hand injury
Name: Injury, dtype: str

In [14]:
unique_df_not_arm1= df_not_arm.loc[
    (df_not_arm['Injury'].str.contains(r'hand', case=False, na=False))
    & ~df_not_arm['Injury'].str.contains(r'fatal|death|died|lost|minor|lacer|abrasion|abraded|kill', case=False, na=False),
    'Injury'
].dropna().unique()
print(unique_df_not_arm1[25:50])
print(len(unique_df_not_arm1.tolist()))

<StringArray>
[                                                              'Puncture wounds to right hand',
                                                                           'Hand/wrist bitten',
                                                                'Cuts to right hand and wrist',
                                       'Hand bitten that was holding a fish PROVOKED INCIDENT',
                                                                 'Cut to index finger of hand',
 'Hand and calf bitten when he jumped off surfboard and landed on the shark PROVOKED INCIDENT',
                                                                 'Bite to left hand and wrist',
                                                             'Severe injuries to leg and hand',
                                                               'Injuries to left arm and hand',
                                                                'Right wrist and hand injured',
                                                                    'Injuries to leg and hand',
                                                                   'Injuries to calf and hand',
                                                                'Injury to right hand / wrist',
                                                                                'Cuts to hand',
                                                                          '5-inch cut to hand',
                                                                  'Injuries to hands and legs',
                                               'Hand bitten by hooked shark PROVOKED INCIDENT',
                                                                  'Injuries to hand and wrist',
                                 'Bruise to leg, cuts to hand sustained when he hit the shark',
                                         'Right hand bitten by hooked shark PROVOKED INCIDENT',
                                                                              'Injury to hand',
                                                        'Puncture wounds to lower arm or hand',
                                                                               'Hand injured?',
                                                  'Buttocks, thigh, left hand & wrist injured',
                                                                   'Severe bite to right hand']
Length: 25, dtype: str
195

In [15]:
unique_df_not_arm2= df_not_arm.loc[
    (df_not_arm['Injury'].str.contains(r'arm', case=False, na=False))
    & ~df_not_arm['Injury'].str.contains(r'fatal|death|died|lost|minor|lacer|abrasion|abraded|kill|hand|die|No injury', case=False, na=False),
    'Injury'
].dropna().unique()
print(unique_df_not_arm2[150:190])
print(len(unique_df_not_arm2.tolist()))

<StringArray>
[                                                                          'Right forearm injured, mid-humeral amputation',
                                                                                                  'Leg, foot & arm bitten',
                          'On 29-Apr-1943 his remains (right forearm & swim trunks) were found in 4.9 m [16'] shark’s gut',
                                                                                     'Right arm severed, left foot bitten',
                                         'Sharks were numerous & took corpses but made no attempts to harm the survivors.',
                                                     'Arm bitten while removing shark from fishing line PROVOKED INCIDENT',
                                                                           'Harpooned shark bit his arm PROVOKED INCIDENT',
 'Arm severed, but survived. Note: Some weeks later he was swimming at the same spot when a shark severed his right foot.',
                                                                                     'Bitten on forearm PROVOKED INCIDENT',
                                                                                          'Back & arm gashed but survived',
                                                         'Captive tiger shark regurgitated his arm in the Coogee Aquarium',
                                                                                 'One man bitten on thigh, another on arm',
                                                        'Injuries to arm, shoulder & chest, took 2 days to reach hospital',
                                                                       'Forearm injured by hooked shark PROVOKED INCIDENT',
                                                                                                'Left arm severely bitten',
                                                                                     'Severe injury to forearm near elbow',
                                                                                                     'Arm & chest injured',
                                                                                                      'Torso & arm bitten',
                                                                                                 'Injuries to chest & arm',
                                                                                 'Arm injured when sharks rammed his boat',
                                                                         'One was bitten on the leg, the other on the arm',
                                                                                                        'Injuries to arm ',
                                                                                                'Human arm found in shark',
                                                                           'Arms broken by hooked shark PROVOKED INCIDENT',
                                                                                            'Left arm severed, leg bitten',
                                                                                               'Arm severed, but survived',
                                                                           'Right hip, buttock, elbow, arm & wrist bitten',
                                                                                                      'Severe bite to arm',
                                                                                                 'Left arm & thigh bitten',
                                                                  'Face & arms injured by hooked shark PROVOKED INCIDENT ',
                                                      'Shark bit his left arm after he grabbed its tail PROVOKED INCIDENT',
                                                                                            'Arm & leg severed, survived ',
                                                                                                       'Head & arm bitten',
                                                                                                     'Arms & legs severed',
                                                                                           'Arms severed, but he survived',
                                                                         'Cut to arm while roping shark PROVOKED INCIDENT',
                                                      'Speared a shark, fell overboard and another shark severed his arm ',
                                                                                           'Lower leg and forearm severed']
Length: 38, dtype: str
188

In [16]:
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Starting reviw and modification of the filtered data frame
arm.head(3)

,index,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,date_parsed,day,month,year
0,15,08-Jan-2026,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,...,NaN,NaN,NaN,NaN,NaN,NaN,1-01-08,8.0,1.0,1.0
1,44,25-Jul-2025,2025.0,Unprovoked,French Polynesia,Nuku Hiva,Taiohae Bay,Swimming,Male child,M,...,NaN,NaN,NaN,NaN,NaN,NaN,1-07-25,25.0,7.0,1.0
2,60,26-May-2025,2025.0,Unprovoked,Vanuatu,South Santo,Espiitu Santo Island,Swimming,Tumas,M,...,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-26,26.0,5.0,2025.0

In [17]:
arm["Injury"].head()

0     Left arm torn off in the attack below the elbow
1    Injuries to right forearm left hand and calf w...
2    Multiple injuries to body one hand and leg bit...
3       both hands bitten off and a bite to left thigh
4            Left hand bitten off and right leg bitten
Name: Injury, dtype: str

In [18]:
arm["Injury"].isnull().sum()

np.int64(0)

In [19]:
#All values are synonims so why not to recall them "Lost Arm"
arm['Injury'] = 'Lost Arm'
arm["Injury"].head(5)

0    Lost Arm
1    Lost Arm
2    Lost Arm
3    Lost Arm
4    Lost Arm
Name: Injury, dtype: str

In [20]:
arm["Location"].unique

<bound method Series.unique of 0                                          Dorsch Beach
1                                           Taiohae Bay
2                                  Espiitu Santo Island
3                                   Thompson Cove Beach
4                          Rosemary Beach Walton County
5                      Water Sound  Beach Walton County
6                                           Leward reef
7                                                 Dahab
8                                               Piedade
9                                    Fernano de Noronha
10                                               Maxixe
11                                Maxixe, Inhambane Bay
12                         Oak Island, Brunswick County
13                         Oak Island, Brunswick County
14                                            Nukudamu
15           Garden Point, Woolloomooloo Sydney Harbour
16                      Brooker Island , Calvados Chain
17                          Gulf Shores, Baldwin County
18                         Chun's Reef, Laniakea, O'ahu
19                                         Highborn Cay
20             Little Glass Shacks, Princeville, Kaua'i
21                                   North Beach, Eilat
22              Japanese fishing boat Taihei Maru No.10
23                                              Mocambo
24                     New Smyrna Beach, Volusia County
25                        Villa del Mar Beach, Veracruz
26                              Lambert’s Beach, Mackay
27                   Pawley’s Island, Georgetown County
28              Longboat Key, Sarasota, Sarasota County
29    Nasigilatu (Near Malasanga, Finschhafen, in th...
30                  Thursday Island Harbour, Queensland
31                                            Kapakapa
32                          San Diego, San Diego County
33                                         Manus Island
34                                  Voh, near meatworks
35                           Mangalia Reef above Touho
36                                    Near Barrow Point
37                       LaPlaya Beach / Vedado, Havana
38                                           Cienfuegos
39                                    Suva Harbor, Suva
40                              Kalepolepo, Kihei, Maui
41                                               Oamaru
42          Calcutta, Hoogly River at  one of the ghats
43    River Sierra Leone, 35 miles  upriver from Fre...
44                                         Carlisle Bay
Name: Location, dtype: str>

In [21]:
#visual check for "broken values"
arm["Country"].unique()

<StringArray>
['US Virgin Islands',  'French Polynesia',           'Vanuatu',
  'Turks and Caicos',               'USA',             'EGYPT',
            'BRAZIL',        'MOZAMBIQUE',              'FIJI',
         'AUSTRALIA',  'PAPUA NEW GUINEA',           'BAHAMAS',
            'ISRAEL',    'PACIFIC OCEAN ',            'MEXICO',
     'NEW CALEDONIA',              'CUBA',       'NEW ZEALAND',
             'INDIA',      'SIERRA LEONE',          'BARBADOS']
Length: 21, dtype: str

In [22]:
#visual check for "broken values"
arm['State'].unique()[0:16]

<StringArray>
[         'Fredricksted Island St Croix',
                             'Nuku Hiva',
                           'South Santo',
 'Near five Cays settlement West Caicos',
                               'Florida',
                 'Providenciales Island',
                           'South Sinai',
                            'Pernambuco',
                    'Inhambane Province',
                        'North Carolina',
                                     nan,
                       'New South Wales',
                 'Louisiade Archipelago',
                               'Alabama',
                                'Hawaii',
                    'Great Exuma Island']
Length: 16, dtype: str

In [23]:
#visual check for "broken values"
arm['State'].unique()[16:50]

<StringArray>
[                             'Red Sea',
 '250 miles southwest of O'ahu, Hawaii',
                             'Veracruz',
                           'Queensland',
                       'South Carolina',
                      'Morobe Province',
                        'Torres Strait',
                     'Central Province',
                           'California',
    'Admiralty Islands, Manus Province',
                       'North Province',
                      'Havana Province',
                  'Cienfuegos Province',
                     'Viti Levu Island',
                         'South Island',
                           '22ºN, 88ºE',
                         'Western Area',
                      'Southwest coast']
Length: 18, dtype: str

In [24]:
#At this point we will calculate variables g1 that will be responsible for representation of data, most of them will be used in project presentation, other is only for internal use
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g1=arm.groupby("Country")
CCC=g1.size()
CCC

Country
AUSTRALIA             4
BAHAMAS               1
BARBADOS              1
BRAZIL                2
CUBA                  2
EGYPT                 1
FIJI                  2
French Polynesia      1
INDIA                 1
ISRAEL                1
MEXICO                2
MOZAMBIQUE            2
NEW CALEDONIA         2
NEW ZEALAND           1
PACIFIC OCEAN         1
PAPUA NEW GUINEA      4
SIERRA LEONE          1
Turks and Caicos      2
US Virgin Islands     1
USA                  12
Vanuatu               1
dtype: int64

In [25]:
g1.size().reset_index(name='count').to_csv('by_countries_count.csv', index=False)

In [26]:
#getting g2 which is country - location - incident count
g2 = arm.groupby(["Country", "Location"]).size()
g2

Country            Location
AUSTRALIA          Garden Point, Woolloomooloo Sydney Harbour                    1
                   Lambert’s Beach, Mackay                                       1
                   Near Barrow Point                                             1
                   Thursday Island Harbour, Queensland                           1
BAHAMAS            Highborn Cay                                                  1
BARBADOS           Carlisle Bay                                                  1
BRAZIL             Fernano de Noronha                                            1
                   Piedade                                                       1
CUBA               Cienfuegos                                                    1
                   LaPlaya Beach / Vedado, Havana                                1
EGYPT              Dahab                                                         1
FIJI               Nukudamu                                                      1
                   Suva Harbor, Suva                                             1
French Polynesia   Taiohae Bay                                                   1
INDIA              Calcutta, Hoogly River at  one of the ghats                   1
ISRAEL             North Beach, Eilat                                            1
MEXICO             Mocambo                                                       1
                   Villa del Mar Beach, Veracruz                                 1
MOZAMBIQUE         Maxixe                                                        1
                   Maxixe, Inhambane Bay                                         1
NEW CALEDONIA      Mangalia Reef above Touho                                     1
                   Voh, near meatworks                                           1
NEW ZEALAND        Oamaru                                                        1
PACIFIC OCEAN      Japanese fishing boat Taihei Maru No.10                       1
PAPUA NEW GUINEA   Brooker Island , Calvados Chain                               1
                   Kapakapa                                                      1
                   Manus Island                                                  1
                   Nasigilatu (Near Malasanga, Finschhafen, in the Huon Gulf)    1
SIERRA LEONE       River Sierra Leone, 35 miles  upriver from Freetown           1
Turks and Caicos   Leward reef                                                   1
                   Thompson Cove Beach                                           1
US Virgin Islands  Dorsch Beach                                                  1
USA                 Kalepolepo, Kihei, Maui                                      1
                   Chun's Reef, Laniakea, O'ahu                                  1
                   Gulf Shores, Baldwin County                                   1
                   Little Glass Shacks, Princeville, Kaua'i                      1
                   Longboat Key, Sarasota, Sarasota County                       1
                   New Smyrna Beach, Volusia County                              1
                   Oak Island, Brunswick County                                  2
                   Pawley’s Island, Georgetown County                            1
                   Rosemary Beach Walton County                                  1
                   San Diego, San Diego County                                   1
                   Water Sound  Beach Walton County                              1
Vanuatu            Espiitu Santo Island                                          1
dtype: int64

In [27]:
#A small modification of Date, Range and Month will help us to get clearer view, additional colums will help for future analysys
arm['Date'] = pd.to_datetime(arm['Date'], errors='coerce')  
arm['DAY'] = arm['Date'].dt.day
arm['Month'] = arm['Date'].dt.month       
arm['MonthName'] = arm['Date'].dt.month_name()

In [28]:
#getting g3 which is incident per month
g3 = arm.groupby(["MonthName"]).size()
g3

MonthName
April        3
August       2
December     3
February     3
January      5
July         5
June         8
March        2
May          2
November     4
October      4
September    4
dtype: int64

In [29]:
#getting g3 which is incident per month per country
g3_1 = arm.groupby(["Country","MonthName"]).size()
g3_1

Country            MonthName
AUSTRALIA          April        1
                   December     1
                   February     1
                   November     1
BAHAMAS            August       1
BARBADOS           March        1
BRAZIL             April        1
                   December     1
CUBA               July         1
                   November     1
EGYPT              September    1
FIJI               January      1
                   March        1
French Polynesia   July         1
INDIA              June         1
ISRAEL             September    1
MEXICO             June         1
                   September    1
MOZAMBIQUE         November     1
                   October      1
NEW CALEDONIA      January      2
NEW ZEALAND        February     1
PACIFIC OCEAN      November     1
PAPUA NEW GUINEA   April        1
                   January      1
                   June         1
                   October      1
SIERRA LEONE       September    1
Turks and Caicos   February     1
                   May          1
US Virgin Islands  January      1
USA                August       1
                   December     1
                   July         3
                   June         5
                   October      2
Vanuatu            May          1
dtype: int64

In [30]:
#A small modification of Date, Range and Month will help us to get clearer view 
season_map = {
    "December":"Winter", "January":"Winter", "February":"Winter",
    "March":"Spring", "April":"Spring", "May":"Spring",
    "June":"Summer", "July":"Summer", "August":"Summer",
    "September":"Autumn", "October":"Autumn", "November":"Autumn"}

In [31]:
#new column 'Season' for better grouping
arm['Season'] = arm['MonthName'].map(season_map)

In [32]:
season_order = ["Winter","Spring","Summer","Autumn"]
arm['Season'] = pd.Categorical(arm['Season'], categories=season_order, ordered=True)

In [33]:
#visual check
arm.groupby("Season").size()

Season
Winter    11
Spring     7
Summer    15
Autumn    12
dtype: int64

In [34]:
#Creating table MonthRange to be more accurate basing on day numeric value column
def part_of_month(day):
    if 1 <= day <= 11: return "First Part"
    if 12 <= day <= 20: return "Middle"
    return "End"

arm['MonthRange'] = arm['DAY'].apply(part_of_month)

arm['MonthRange'] = arm['MonthRange'] + " of " + arm['MonthName']

In [35]:
#getting g4 which is incident per month range
g4 = arm.groupby(["MonthRange"]).size()
g4

MonthRange
End of December            3
End of July                2
End of March               2
End of May                 2
End of November            2
End of September           2
First Part of April        1
First Part of August       1
First Part of February     2
First Part of January      5
First Part of June         4
First Part of November     1
First Part of October      2
First Part of September    1
Middle of April            2
Middle of August           1
Middle of February         1
Middle of July             3
Middle of June             4
Middle of November         1
Middle of October          2
Middle of September        1
dtype: int64

In [36]:
#getting g5 which is incident per month range per country
g5 = arm.groupby(["Country","MonthRange"]).size()
g5

Country            MonthRange
AUSTRALIA          End of December            1
                   First Part of February     1
                   Middle of April            1
                   Middle of November         1
BAHAMAS            First Part of August       1
BARBADOS           End of March               1
BRAZIL             End of December            1
                   Middle of April            1
CUBA               End of November            1
                   Middle of July             1
EGYPT              Middle of September        1
FIJI               End of March               1
                   First Part of January      1
French Polynesia   End of July                1
INDIA              Middle of June             1
ISRAEL             First Part of September    1
MEXICO             End of September           1
                   First Part of June         1
MOZAMBIQUE         First Part of November     1
                   First Part of October      1
NEW CALEDONIA      First Part of January      2
NEW ZEALAND        Middle of February         1
PACIFIC OCEAN      End of November            1
PAPUA NEW GUINEA   First Part of April        1
                   First Part of January      1
                   Middle of June             1
                   Middle of October          1
SIERRA LEONE       End of September           1
Turks and Caicos   End of May                 1
                   First Part of February     1
US Virgin Islands  First Part of January      1
USA                End of December            1
                   End of July                1
                   First Part of June         3
                   First Part of October      1
                   Middle of August           1
                   Middle of July             2
                   Middle of June             2
                   Middle of October          1
Vanuatu            End of May                 1
dtype: int64

In [37]:
#to file to use in presentation
df_g5 = g5.reset_index(name='Count')
df_g5.to_excel(Path("g5_counts.xlsx"), index=False, sheet_name='g5_counts')

In [38]:
#visual check
arm.groupby(["Country","MonthRange","Activity"]).size()

Country            MonthRange               Activity
AUSTRALIA          End of December          Standing                                                                          1
                   First Part of February   Diving, but on the surface when bitten by the shark                               1
                   Middle of April          Swimming between  anchored  pearling luggers                                      1
                   Middle of November       Pearl diving                                                                      1
BAHAMAS            First Part of August     Spearfishing                                                                      1
BARBADOS           End of March             Swimming                                                                          1
BRAZIL             End of December          Scuba diving                                                                      1
                   Middle of April          Swimming                                                                          1
CUBA               End of November          Fishing                                                                           1
                   Middle of July           Swimming                                                                          1
EGYPT              Middle of September      Swimming                                                                          1
FIJI               End of March             Diving and fishing                                                                1
                   First Part of January    Diving for coins tossed from passenger ship                                       1
French Polynesia   End of July              Swimming                                                                          1
INDIA              Middle of June           Bathing                                                                           1
ISRAEL             First Part of September  Swimming                                                                          1
MEXICO             End of September         Swimming                                                                          1
                   First Part of June       Swimming                                                                          1
MOZAMBIQUE         First Part of November   Fishing                                                                           1
                   First Part of October    Fishing                                                                           1
NEW CALEDONIA      First Part of January    Helmet diving, collecting trochus shell                                           1
                                            Spearfishing, but walking carrying fish on end of speargun                        1
NEW ZEALAND        Middle of February       Floating on his back                                                              1
PACIFIC OCEAN      End of November          Hauling dead shark aboard, when another shark leapt out of the water & bit him    1
PAPUA NEW GUINEA   First Part of April      Fishing, holding fish in his left hand                                            1
                   First Part of January    Spearfishing                                                                      1
                   Middle of October        Spearfishing, holding 5' speared fish                                             1
SIERRA LEONE       End of September         British ship, Britannia,  was loading lumber. He was bathing                      1
Turks and Caicos   End of May               snorkelling                                                                       1
                   First Part of February   Swimming                                                                          1
US Virgin Islands  First Part of January    Snorkeling                                                                        1
USA                End of December          Lying on surfboard                                                                1
                   End of July              Swimming, ducking for shells in water 0.9 m deep                                  1
                   First Part of June       Swimming                                                                          1
                                            Swimming                                                                          1
                                            Wading                                                                            1
                   First Part of October    Diving, retrieving fish caught in net                                             1
                   Middle of August         Wading                                                                            1
                   Middle of July           Bathing                                                                           1
                                            Fishing                                                                           1
                   Middle of June           Wading                                                                            2
                   Middle of October        Body boarding                                                                     1
Vanuatu            End of May               Swimming                                                                          1
dtype: int64

In [39]:
#visual check
arm[["Date", "Country", "Activity","Location"]].head(5)

        Date            Country    Activity                      Location
0 2026-01-08  US Virgin Islands  Snorkeling                  Dorsch Beach
1 2025-07-25   French Polynesia    Swimming                   Taiohae Bay
2 2025-05-26            Vanuatu    Swimming          Espiitu Santo Island
3 2025-02-07   Turks and Caicos    Swimming           Thompson Cove Beach
4 2024-06-07                USA      Wading  Rosemary Beach Walton County

In [40]:
#visual check
arm["Activity"].unique()

<StringArray>
[                                                                    'Snorkeling',
                                                                       'Swimming',
                                                                         'Wading',
                                                                    'snorkelling',
                                                                   'Scuba diving',
                                                                        'Fishing',
                                                             'Diving and fishing',
                            'Diving, but on the surface when bitten by the shark',
                                                                              nan,
                                                                      'Swimming ',
                                                             'Lying on surfboard',
                                                                   'Spearfishing',
                                                                  'Body boarding',
 'Hauling dead shark aboard, when another shark leapt out of the water & bit him',
                                                                        'Bathing',
                                                                       'Standing',
                               'Swimming, ducking for shells in water 0.9 m deep',
                                         'Fishing, holding fish in his left hand',
                                   'Swimming between  anchored  pearling luggers',
                                          'Spearfishing, holding 5' speared fish',
                     'Spearfishing, but walking carrying fish on end of speargun',
                                        'Helmet diving, collecting trochus shell',
                                                                   'Pearl diving',
                                    'Diving for coins tossed from passenger ship',
                                         'Diving, retrieving fish caught in net ',
                                                           'Floating on his back',
                   'British ship, Britannia,  was loading lumber. He was bathing']
Length: 27, dtype: str

In [41]:
#A small monkey job to get structural equipment understanding, assigning equipment regarding activity situation during attack
equipment_map = {
    "Snorkeling": "Scuba set + WJ", "Swimming": "WJ", "Wading": "NS",
    "snorkelling": "Scuba set + WJ", "Scuba diving": "Scuba set + WJ", "Fishing": "WJ",
    "Diving / fishing": "BScuba set + WJ", "Diving, but on the surface when bitten by the shark": "Scuba set + WJ", "Swimming": "WJ",
    "Lying on surfboard": "WJ", "Spearfishing": "Scuba set + WJ", "Body boarding": "WJ","Hauling dead shark aboard, when another shark leapt out of the water & bit him": "WJ",
    "Bathing": "WJ","Standing": "NS","Swimming, ducking for shells in water 0.9 m deep": "WJ","Fishing, holding fish in his left hand": "WJ",
    "Swimming between  anchored  pearling luggers": "WJ","Spearfishing, holding 5' speared fish": "Scuba set + WJ","Spearfishing, but walking carrying fish on end of speargun": "NS",
    "Helmet diving, collecting trochus shell": "Scuba set + WJ", "Pearl diving": "Scuba set + WJ", "Diving for coins tossed from passenger ship": "Scuba set + WJ",
    "Diving, retrieving fish caught in net": "Scuba set + WJ", "Floating on his back": "WJ", "British ship, Britannia,  was loading lumber. He was bathing": "WJ"}

equipment_map_normalized = {k.lower(): v for k, v in equipment_map.items()}
arm['Equipment Needed'] = (arm['Activity'].str.strip().str.lower().map(equipment_map_normalized).fillna('Unknown'))

In [42]:
#visual check
arm[["Country", "Activity", "Equipment Needed"]].head(5)

             Country    Activity Equipment Needed
0  US Virgin Islands  Snorkeling   Scuba set + WJ
1   French Polynesia    Swimming               WJ
2            Vanuatu    Swimming               WJ
3   Turks and Caicos    Swimming               WJ
4                USA      Wading               NS

In [43]:
#Getting per cent of underwater arm incidents comparing to total arm incidents
scuba_count = arm['Equipment Needed'].str.contains('Scuba set', na=False).sum()
genCNT = arm['Equipment Needed'].notna().sum()
pct_genCNT = scuba_count / genCNT * 100 if genCNT else 0
print(f"We will need Scuba : {scuba_count} from {genCNT} ({pct_genCNT:.2f}%)")

We will need Scuba : 11 from 45 (24.44%)

In [44]:
#getting g6 which is incident per Equipment Needed per country
g6 = arm.groupby(["Country","Equipment Needed"]).size()
g6

Country            Equipment Needed
AUSTRALIA          NS                  1
                   Scuba set + WJ      2
                   WJ                  1
BAHAMAS            Scuba set + WJ      1
BARBADOS           WJ                  1
BRAZIL             Scuba set + WJ      1
                   WJ                  1
CUBA               WJ                  2
EGYPT              WJ                  1
FIJI               Scuba set + WJ      1
                   Unknown             1
French Polynesia   WJ                  1
INDIA              WJ                  1
ISRAEL             WJ                  1
MEXICO             WJ                  2
MOZAMBIQUE         WJ                  2
NEW CALEDONIA      NS                  1
                   Scuba set + WJ      1
NEW ZEALAND        WJ                  1
PACIFIC OCEAN      WJ                  1
PAPUA NEW GUINEA   Scuba set + WJ      2
                   Unknown             1
                   WJ                  1
SIERRA LEONE       WJ                  1
Turks and Caicos   Scuba set + WJ      1
                   WJ                  1
US Virgin Islands  Scuba set + WJ      1
USA                NS                  4
                   Scuba set + WJ      1
                   WJ                  7
Vanuatu            WJ                  1
dtype: int64

In [45]:
#getting g7 which is 'Hand Eaters' attacks in month range
g7 = arm.groupby('MonthRange').size().to_dict()
for k, v in g7.items():
    print(f"'Hand Eaters' attacks in the {k}: {v}")

'Hand Eaters' attacks in the End of December: 3
'Hand Eaters' attacks in the End of July: 2
'Hand Eaters' attacks in the End of March: 2
'Hand Eaters' attacks in the End of May: 2
'Hand Eaters' attacks in the End of November: 2
'Hand Eaters' attacks in the End of September: 2
'Hand Eaters' attacks in the First Part of April: 1
'Hand Eaters' attacks in the First Part of August: 1
'Hand Eaters' attacks in the First Part of February: 2
'Hand Eaters' attacks in the First Part of January: 5
'Hand Eaters' attacks in the First Part of June: 4
'Hand Eaters' attacks in the First Part of November: 1
'Hand Eaters' attacks in the First Part of October: 2
'Hand Eaters' attacks in the First Part of September: 1
'Hand Eaters' attacks in the Middle of April: 2
'Hand Eaters' attacks in the Middle of August: 1
'Hand Eaters' attacks in the Middle of February: 1
'Hand Eaters' attacks in the Middle of July: 3
'Hand Eaters' attacks in the Middle of June: 4
'Hand Eaters' attacks in the Middle of November: 1
'Hand Eaters' attacks in the Middle of October: 2
'Hand Eaters' attacks in the Middle of September: 1

In [46]:
#getting g8 which is count of Equipment Needed in month range
g8 = arm.groupby(['MonthRange','Equipment Needed']).size()
g8

MonthRange               Equipment Needed
End of December          NS                  1
                         Scuba set + WJ      1
                         WJ                  1
End of July              WJ                  2
End of March             Unknown             1
                         WJ                  1
End of May               Scuba set + WJ      1
                         WJ                  1
End of November          WJ                  2
End of September         WJ                  2
First Part of April      WJ                  1
First Part of August     Scuba set + WJ      1
First Part of February   Scuba set + WJ      1
                         WJ                  1
First Part of January    NS                  1
                         Scuba set + WJ      4
First Part of June       NS                  1
                         WJ                  3
First Part of November   WJ                  1
First Part of October    Scuba set + WJ      1
                         WJ                  1
First Part of September  WJ                  1
Middle of April          WJ                  2
Middle of August         NS                  1
Middle of February       WJ                  1
Middle of July           WJ                  3
Middle of June           NS                  2
                         Unknown             1
                         WJ                  1
Middle of November       Scuba set + WJ      1
Middle of October        Scuba set + WJ      1
                         WJ                  1
Middle of September      WJ                  1
dtype: int64

In [47]:
#getting g9 which Underwater attacks in the month range
mask = arm['Equipment Needed'].str.contains('Scuba set', na=False)
g9 = arm.loc[mask].groupby('MonthRange').size().to_dict()
for k, v in g9.items():
    print(f"Underwater attacks in the {k}: {v}")

Underwater attacks in the End of December: 1
Underwater attacks in the End of May: 1
Underwater attacks in the First Part of August: 1
Underwater attacks in the First Part of February: 1
Underwater attacks in the First Part of January: 4
Underwater attacks in the First Part of October: 1
Underwater attacks in the Middle of November: 1
Underwater attacks in the Middle of October: 1

In [48]:
#getting g11 which is "fancy" view of arm incidents per month range per country 
g11 = arm.groupby(['Country','MonthRange']).size().to_dict()

from collections import defaultdict
by_country = defaultdict(list)
for (country, month), count in g11.items():
    by_country[country].append((month, count))

for country, items in by_country.items():
    print(country)                      
    for month, count in items:
        print(f"  {month}: {count}")    
    print()

AUSTRALIA
  End of December: 1
  First Part of February: 1
  Middle of April: 1
  Middle of November: 1

BAHAMAS
  First Part of August: 1

BARBADOS
  End of March: 1

BRAZIL
  End of December: 1
  Middle of April: 1

CUBA
  End of November: 1
  Middle of July: 1

EGYPT
  Middle of September: 1

FIJI
  End of March: 1
  First Part of January: 1

French Polynesia
  End of July: 1

INDIA
  Middle of June: 1

ISRAEL
  First Part of September: 1

MEXICO
  End of September: 1
  First Part of June: 1

MOZAMBIQUE
  First Part of November: 1
  First Part of October: 1

NEW CALEDONIA
  First Part of January: 2

NEW ZEALAND
  Middle of February: 1

PACIFIC OCEAN
  End of November: 1

PAPUA NEW GUINEA
  First Part of April: 1
  First Part of January: 1
  Middle of June: 1
  Middle of October: 1

SIERRA LEONE
  End of September: 1

Turks and Caicos
  End of May: 1
  First Part of February: 1

US Virgin Islands
  First Part of January: 1

USA
  End of December: 1
  End of July: 1
  First Part of June: 3
  First Part of October: 1
  Middle of August: 1
  Middle of July: 2
  Middle of June: 2
  Middle of October: 1

Vanuatu
  End of May: 1

In [49]:
#visual check
arm["Season"].head()

0    Winter
1    Summer
2    Spring
3    Winter
4    Summer
Name: Season, dtype: category
Categories (4, str): ['Winter' < 'Spring' < 'Summer' < 'Autumn']

In [50]:
#getting g13 which is 'Hand Eaters' attacks per Season
g13 = arm.groupby('Season').size().to_dict()
for k, v in g13.items():
    print(f"'Hand Eaters' attacks in the {k}: {v}")

'Hand Eaters' attacks in the Winter: 11
'Hand Eaters' attacks in the Spring: 7
'Hand Eaters' attacks in the Summer: 15
'Hand Eaters' attacks in the Autumn: 12

In [51]:
#getting General missed arms incidents per cent
arm_count = arm['Date'].count()
g12 = df['Date'].notna().sum()
pct_g12 = arm_count / g12 * 100 if g12 else 0
print(f"General missed arms incidents : {arm_count} from {g12} ({pct_g12:.2f}%)")

General missed arms incidents : 45 from 7082 (0.64%)

In [57]:
#getting g14 which is country - location - incident count
g14 = arm.groupby(["Country", "Location","MonthName"]).size()
g14

Country            Location                                                    MonthName
AUSTRALIA          Garden Point, Woolloomooloo Sydney Harbour                  February     1
                   Lambert’s Beach, Mackay                                     December     1
                   Near Barrow Point                                           November     1
                   Thursday Island Harbour, Queensland                         April        1
BAHAMAS            Highborn Cay                                                August       1
BARBADOS           Carlisle Bay                                                March        1
BRAZIL             Fernano de Noronha                                          December     1
                   Piedade                                                     April        1
CUBA               Cienfuegos                                                  November     1
                   LaPlaya Beach / Vedado, Havana                              July         1
EGYPT              Dahab                                                       September    1
FIJI               Nukudamu                                                    March        1
                   Suva Harbor, Suva                                           January      1
French Polynesia   Taiohae Bay                                                 July         1
INDIA              Calcutta, Hoogly River at  one of the ghats                 June         1
ISRAEL             North Beach, Eilat                                          September    1
MEXICO             Mocambo                                                     June         1
                   Villa del Mar Beach, Veracruz                               September    1
MOZAMBIQUE         Maxixe                                                      November     1
                   Maxixe, Inhambane Bay                                       October      1
NEW CALEDONIA      Mangalia Reef above Touho                                   January      1
                   Voh, near meatworks                                         January      1
NEW ZEALAND        Oamaru                                                      February     1
PACIFIC OCEAN      Japanese fishing boat Taihei Maru No.10                     November     1
PAPUA NEW GUINEA   Brooker Island , Calvados Chain                             June         1
                   Kapakapa                                                    October      1
                   Manus Island                                                January      1
                   Nasigilatu (Near Malasanga, Finschhafen, in the Huon Gulf)  April        1
SIERRA LEONE       River Sierra Leone, 35 miles  upriver from Freetown         September    1
Turks and Caicos   Leward reef                                                 May          1
                   Thompson Cove Beach                                         February     1
US Virgin Islands  Dorsch Beach                                                January      1
USA                 Kalepolepo, Kihei, Maui                                    October      1
                   Chun's Reef, Laniakea, O'ahu                                December     1
                   Gulf Shores, Baldwin County                                 June         1
                   Little Glass Shacks, Princeville, Kaua'i                    October      1
                   Longboat Key, Sarasota, Sarasota County                     July         1
                   New Smyrna Beach, Volusia County                            July         1
                   Oak Island, Brunswick County                                June         2
                   Pawley’s Island, Georgetown County                          August       1
                   Rosemary Beach Walton County                                June         1
                   San Diego, San Diego County                                 July         1
                   Water Sound  Beach Walton County                            June         1
Vanuatu            Espiitu Santo Island                                        May          1
dtype: int64